import Image from 'next/image'
import dribbbleLogo from '../assets/dribbble.png';
import mediumLogo from '../assets/medium.png';
import threadsLogo from '../assets/threads.png';
import figmaLogo from '../assets/figma.png';
import workpath from '../assets/wp.png';

export const metadata = {
  title: 'Nick M. Jones',
  description: 'Generated by create next app',
}
export default function Home() {
  return (
    <main>

      <div id="intro" className="min-h-screen flex flex-col md:flex-row justify-center items-center bg-[#1f1d2e] p-16 md:p-24 gap-4">
        <div class="w-2/3"> 
          <h1 className="w-full text-2xl md:text-8xl text-violet-200 py-12 font-bold">
            <span class="leading-tighter">I make things <br/>people like.</span>
          </h1>
          <ul className="flex flex-row gap-4 text-sm font-bold text-slate-700 md:text-lg">
            <li>
              <Image
                src={dribbbleLogo}
                alt="Dribbble logo"
                width={32}
                height={32}
              />
            </li>
            <li>
              <Image
                src={figmaLogo}
                alt="Figma logo"
                width={32}
                height={32}
              />
            </li>
            <li>
              <Image
                src={threadsLogo}
                alt="Threads logo"
                width={32}
                height={32}
              />
            </li>
            <li>
              <Image
                src={mediumLogo}
                alt="Medium logo"
                width={32}
                height={32}
              />
            </li>
          </ul>
        </div>
        <div>
          <Image
            src={workpath}
            width={680}
            height={585}
            alt="Workpath screenshot"
          />
        </div>
      </div>

      <div id="copy" className="flex flex-col justify-center bg-[#1f1d2e] py-16 md:py-16 px-16 md:px-32 text-[#eb6f92]">
        <h2 class="text-3xl font-bold text-center leading-relaxed">
          I'm a veteran product, UX, and graphic designer currently in Providence (by way of NYC). Twenty+ years in the pixel mines. Dad, husband, musician, cook, camera operator, and next-life coffee shop owner.
        </h2>
      </div>

      <div className="flex flex-col md:flex-row text-violet-200 bg-[#1f1d2e] p-24 gap-4">

        <div className="rounded-xl bg-[#26233a] p-8 w-1/2">
          <h3 className="mb-4 text-base text-[#c4a7e7]">Writing</h3>
          <div className="mb-4 flex-col space-y-1">
            <a
              href="https://medium.com/design-bootcamp/listening-to-pavement-with-a-migraine-or-let-go-or-be-dragged-d3223a2bc6d6"
              target="_blank"
              rel="noreferrer"
            >
              Listening to Pavement with a migraine: or, “Let go or be dragged.”
            </a>
            <h4 className="text-sm text-[#6e6a86]">Medium - Oct. 2023</h4>
          </div>
          <div className="mb-4 flex-col space-y-1">
            <a
              href="https://medium.com/design-bootcamp/apples-dynamic-island-is-a-master-class-in-product-problem-solving-embracing-constraints-6e4e8ec00dc9"
              target="_blank"
              rel="noreferrer"
            >
              Apple’s ‘Dynamic Island’ is a master class in product problem
              solving & embracing constraints.
            </a>
            <h4 className="text-sm text-[#6e6a86]">Medium - Sept. 2022</h4>
          </div>
          <div className="mb-4 flex-col space-y-1">
            <a
              href="https://medium.com/pragmatic-ux/evolution-vs-revolution-and-the-zen-of-just-f-cking-starting-a807fab51647"
              target="_blank"
              rel="noreferrer"
            >
              “Evolution vs. Revolution” and the Zen of just f*cking starting
            </a>
            <h4 className="text-sm text-[#6e6a86]">Medium - Apr. 2018</h4>
          </div>
        </div>

        <div className="rounded-xl bg-[#26233a] p-8 w-1/2">
          <h3 className="mb-4 text-base text-[#c4a7e7]">Music</h3>
          <p>
            I release ambient/electronic music under the name Glitch
            Ensemble&mdash;an effort to make music that isn't guitar-based, and
            that's more rooted in loops, drones, and atmosphere.
          </p>

          <div className="flex w-full flex-row items-center gap-6 py-4">
            <div className="w-44">Call It A Night - Single</div>
            <div className="text-sm text-[#6e6a86]">
              <a
                href="https://music.apple.com/us/album/call-it-a-night-single/1707891572"
                target="_blank"
                rel="noreferrer"
              >
                Apple
              </a>
            </div>
            <div className="text-sm text-[#6e6a86]">
              <a
                href="https://open.spotify.com/album/0OaM9NakFZ7PjFI5LSJQ1f?si=MM0QLL3iTRismnmVaF1Zug"
                target="_blank"
                rel="noreferrer"
              >
                Spotify
              </a>
            </div>
          </div>

          <div className="flex w-full flex-row items-center gap-6 py-4">
            <div className="w-44">Pretend Numbers EP</div>
            <div className="text-sm text-[#6e6a86]">
              <a
                href="https://music.apple.com/us/album/pretend-numbers-ep/1703509006"
                target="_blank"
                rel="noreferrer"
              >
                Apple
              </a>
            </div>
            <div className="text-sm text-[#6e6a86]">
              <a
                href="https://open.spotify.com/album/5xus5iMkRSYd6tjS7EaKtx?si=HC0ksPCoREyDtKpIDdoVfA"
                target="_blank"
                rel="noreferrer"
              >
                Spotify
              </a>
            </div>
          </div>
        </div>
      </div>

    </main>
  );
}
