export const metadata = {
  title: 'Nick M. Jones',
  description: 'Generated by create next app',
}
export default function Home() {
  return (
    <main>

      <div className="flex h-1/2 flex-col justify-center space-y-12 bg-stone-100 px-8 py-8 md:h-[580px] md:px-24 md:py-24">
        <h2 className="inline-block w-full bg-gradient-to-r from-blue-600 via-fuchsia-500 to-indigo-400 bg-clip-text text-xl font-bold text-slate-700 text-transparent md:w-2/3 md:text-5xl">
          Nick Jones is a veteran product, UX, and graphic designer currently in
          Providence. Twenty+ years in the pixel mines. Dad, husband, musician,
          cook, camera operator, and next-life coffee shop owner.
        </h2>
        <ul className="flex flex-row gap-4 text-sm font-bold text-slate-700 md:text-lg">
          <li>Dribbble</li>
          <li>Figma</li>
          <li>Threads</li>
          <li>Medium</li>
        </ul>
      </div>

      <div className="flex flex-col text-slate-300 bg-slate-800">
        <div className="mt-8 w-full px-8 py-8 md:px-24 md:py-4">
          <h3 className="text-base text-blue-400">Working</h3>
          <div className="flex w-full flex-row gap-6 py-4 md:w-1/5">
            <div className="w-16">2021</div>
            <div className="w-16">Present</div>
            <div className="w-32">Life360/Tile</div>
          </div>
          <p className="w-full text-sm text-slate-500 md:w-1/2">
            As Senior Product Designer at Life360/Tile, I own all design for
            both tile.com and life360.com. In 2023 I lead a series of large
            scale redesigns of the end-to-end Tile ecommerce site, including the
            homepage and all product pages.
          </p>
          <div className="flex w-full flex-row gap-6 py-4 md:w-1/5">
            <div className="w-16">2019</div>
            <div className="w-16">2020</div>
            <div className="w-32">Workpath</div>
          </div>
          <div className="flex w-full flex-row gap-6 py-4 md:w-1/5">
            <div className="w-16">2018</div>
            <div className="w-16">2019</div>
            <div className="w-32">Event Farm</div>
          </div>
          <div className="flex w-full flex-row gap-6 py-4 md:w-1/5">
            <div className="w-16">2016</div>
            <div className="w-16">2018</div>
            <div className="w-32">CustomInk</div>
          </div>
        </div>

        <div className="w-full px-8 py-8 md:w-2/3 md:px-24 md:py-4">
          <h3 className="mb-4 text-base text-blue-400">Writing</h3>
          <div className="mb-4 flex-col space-y-1">
            <a
              href="https://medium.com/design-bootcamp/listening-to-pavement-with-a-migraine-or-let-go-or-be-dragged-d3223a2bc6d6"
              target="_blank"
              rel="noreferrer"
            >
              Listening to Pavement with a migraine: or, “Let go or be dragged.”
              &#x2197;
            </a>
            <h4 className="text-sm text-slate-500">Medium • Oct. 2023</h4>
          </div>
          <div className="mb-4 flex-col space-y-1">
            <a
              href="https://medium.com/design-bootcamp/apples-dynamic-island-is-a-master-class-in-product-problem-solving-embracing-constraints-6e4e8ec00dc9"
              target="_blank"
              rel="noreferrer"
            >
              Apple’s ‘Dynamic Island’ is a master class in product problem
              solving & embracing constraints. &#x2197;
            </a>
            <h4 className="text-sm text-slate-500">Medium • Sept. 2022</h4>
          </div>
          <div className="mb-4 flex-col space-y-1">
            <a
              href="https://medium.com/pragmatic-ux/evolution-vs-revolution-and-the-zen-of-just-f-cking-starting-a807fab51647"
              target="_blank"
              rel="noreferrer"
            >
              “Evolution vs. Revolution” and the Zen of just f*cking starting
              &#x2197;
            </a>
            <h4 className="text-sm text-slate-500">Medium • Apr. 2018</h4>
          </div>
        </div>

        <div className="w-full px-8 py-8 md:w-2/3 md:px-24 md:py-4">
          <h3 className="mb-4 text-base text-blue-400">Music</h3>
          <p>
            I release ambient/electronic music under the name Glitch
            Ensemble&mdash;an effort to make music that isn't guitar-based, and
            that's more rooted in loops, drones, and atmosphere.
          </p>

          <div className="flex w-full flex-row items-center gap-6 py-4">
            <div className="w-44">Call It A Night - Single</div>
            <div className="text-sm text-slate-500">
              <a
                href="https://music.apple.com/us/album/call-it-a-night-single/1707891572"
                target="_blank"
                rel="noreferrer"
              >
                Apple &#x2197;
              </a>
            </div>
            <div className="text-sm text-slate-500">
              <a
                href="https://open.spotify.com/album/0OaM9NakFZ7PjFI5LSJQ1f?si=MM0QLL3iTRismnmVaF1Zug"
                target="_blank"
                rel="noreferrer"
              >
                Spotify &#x2197;
              </a>
            </div>
          </div>

          <div className="flex w-full flex-row items-center gap-6 py-4">
            <div className="w-44">Pretend Numbers EP</div>
            <div className="text-sm text-slate-500">
              <a
                href="https://music.apple.com/us/album/pretend-numbers-ep/1703509006"
                target="_blank"
                rel="noreferrer"
              >
                Apple &#x2197;
              </a>
            </div>
            <div className="text-sm text-slate-500">
              <a
                href="https://open.spotify.com/album/5xus5iMkRSYd6tjS7EaKtx?si=HC0ksPCoREyDtKpIDdoVfA"
                target="_blank"
                rel="noreferrer"
              >
                Spotify &#x2197;
              </a>
            </div>
          </div>
        </div>
      </div>

    </main>
  );
}
